// Common defines for both GLSL and C++
// must compile under both

#ifndef LAVOS_COMMON_GLSL_CPP_H
#define LAVOS_COMMON_GLSL_CPP_H

#define DESCRIPTOR_SET_INDEX_COMMON		0
#define DESCRIPTOR_SET_INDEX_MATERIAL	1

#define MAX_SPOT_LIGHTS_COUNT 16

#define DESCRIPTOR_SET_COMMON_BINDING_MATRIX_BUFFER			0
#define DESCRIPTOR_SET_COMMON_BINDING_LIGHTING_BUFFER		1
#define DESCRIPTOR_SET_COMMON_BINDING_CAMERA_BUFFER			2
#define DESCRIPTOR_SET_COMMON_BINDING_SPOT_LIGHT_SHADOW_TEX	3

#define SHADOW_MSM 1

#endif //LAVOS_COMMON_GLSL_CPP_H
