language: cpp
sudo: false
dist: trusty

addons:
  apt:
    sources:
      ubuntu-toolchain-r-test
    packages:
      - g++-7
      - ninja-build

      # GLFW
      - libxrandr-dev
      - libxinerama-dev
      - libxcursor-dev
      - libxi-dev

      # PCL
      - libeigen3-dev
      - libboost-dev
      - libboost-system-dev
      - libboost-filesystem-dev
      - libboost-thread-dev
      - libboost-date-time-dev
      - libboost-iostreams-dev
      - libboost-serialization-dev
      - libboost-chrono-dev
      - libflann-dev

env:
  - CI_DEPS_URL="https://github.com/thestr4ng3r/lavos-ci-deps/releases/download/v2/lavos-ci-deps-linux-x86_64.tar.gz"
    VULKAN_VERSION=1.1.73.0

before_install:
  - export CC=gcc-7
  - export CXX=g++-7

install:
  - cd thirdparty || exit 1
  - wget $CI_DEPS_URL || exit 1
  - tar -xf lavos-ci-deps-linux-x86_64.tar.gz || exit 1
  - export VULKAN_SDK_PREFIX=`pwd`/vulkansdk/$VULKAN_VERSION/x86_64
  - export SHADERC_PREFIX=`pwd`/shaderc
  - export PCL_PREFIX=`pwd`/pcl
  - cd $TRAVIS_BUILD_DIR || exit 1

script:
  - mkdir build && cd build || exit 1
  - cmake
    -GNinja
    -DCMAKE_BUILD_TYPE=Release
    -DCMAKE_PREFIX_PATH="$VULKAN_SDK_PREFIX;$SHADERC_PREFIX;$PCL_PREFIX"
    -DLAVOS_BUILD_SHELL_GLFW=ON
    -DLAVOS_BUILD_DEMOS=ON
    -DLAVOS_BUILD_POINT_CLOUD_DEMO=ON
    ..
    || exit 1
  - ninja -j 4 || exit 1